a = input("Digita algo! ")
print("O tipo primitido desse valor é", type(a))
print("Só tem espaços?", a.isspace())
print(" è um numero?", a.isnumeric())
print("É alfabetico?", a.isalpha())
print("É Alpa numerico", a.isalnum())
print("Esta em Maiuscila?", a.isupper())
print('Esta em minuscula?', a.islower())
print('Esta capiutalizsada', a.istitle())